import Head from 'next/head';
import { useAppSelector } from '@/redux/hooks';
import { counterApiSlice, counterSlice } from '@/redux/reducers';
import CounterApi from '@/components/CounterApi';
import Counter from '@/components/Counter';
import styles from '@/styles/Home.module.css';

export default function Home() {
  const appState = useAppSelector((state) => state);

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.info}>
        Change the counters and refresh the page to see the difference
      </div>
      <main className={styles.main}>
        <div className={styles.counters}>
          <div className={styles.store}>
            <Counter />
          </div>
          <div className={styles.storeApi}>
            <CounterApi />
          </div>
        </div>
        <div className={styles.storeObject}>
          <h3>Store:</h3>
          <pre>
            {JSON.stringify(
              appState,
              [counterSlice.name, counterApiSlice.name, 'loading', 'value', 'error'],
              2
            )}
          </pre>
          {/* <pre>{JSON.stringify(appState, null, 2)}</pre> */}
        </div>
      </main>
    </div>
  );
}
